files:
  - url: ""
    time: 1658282851319.yml
    name: config.yaml
    selected: []
  - time: 1658283139554.yml
    name: Clash_1658283139.yaml
    url: https://www.sstank.top/link/tgCHHnnaqEnsiYV3?clash=1
    selected:
      - name: GLOBAL
        now: æ–°åŠ å¡1-v2ray
      - name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
        now: æ–°åŠ å¡1-Trojan
      - name: ğŸŒ å›½å¤–åª’ä½“
        now: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - name: ğŸ“² ç”µæŠ¥ä¿¡æ¯
        now: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - name: â“‚ï¸ å¾®è½¯æœåŠ¡
        now: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - name: ğŸ è‹¹æœæœåŠ¡
        now: ğŸ¯ å…¨çƒç›´è¿
      - name: ğŸ“¢ è°·æ­ŒFCM
        now: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - name: ğŸ¯ å…¨çƒç›´è¿
        now: DIRECT
      - name: ğŸ›‘ å…¨çƒæ‹¦æˆª
        now: REJECT
      - name: ğŸƒ åº”ç”¨å‡€åŒ–
        now: REJECT
      - name: ğŸŸ æ¼ç½‘ä¹‹é±¼
        now: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
    interval: 24
    subInfo:
      upload: 2725321005
      download: 22682610564
      total: 214748364800
      expire: 1709777451
    mode: rule
    cron: ""
    headers: ""
index: 1
